version: "3.8"
services:
  frontend:
    build: .
    container_name: blog-frontend
    ports:
      - "3001:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./build:/usr/share/nginx/html:ro
