name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: |
          if [ -f package.json ] && npm run | grep -q 'lint'; then npm run lint; else echo "No lint script"; fi

      # Uncomment to enable tests
      # - name: Run tests
      #   env:
      #     CI: true
      #   run: |
      #     if [ -f package.json ] && npm run | grep -q 'test'; then npm test -- --watchAll=false; else echo "No test script"; fi

      - name: Build
        run: npm run build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /home/ubuntu/devtools/blog-front &&
          if [ ! -d ".git" ]; then
            git clone https://github.com/leograva/blog-front.git .;
          else
            git pull origin main;
          fi
          # Limpa containers antigos e imagens órfãs
          docker compose down -v --remove-orphans || true
          docker system prune -af || true
          docker compose pull
          docker compose up -d --build
          EOF
