name: Deploy to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy project files to VPS
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/blog-front/

      - name: Install Docker & Docker Compose on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
            if ! command -v docker >/dev/null; then
              curl -fsSL https://get.docker.com | sh
            fi
            if ! command -v docker-compose >/dev/null; then
              sudo apt-get update && sudo apt-get install -y docker-compose
            fi
            sudo usermod -aG docker $USER
          '

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
            cd ~/blog-front && docker-compose up -d --build
          '
